import type { PersonaPerspective } from "./venture-domain";

export const personaCouncil: readonly PersonaPerspective[] = [
  {
    id: "overwhelmed-caregiver",
    name: "The Overwhelmed Caregiver",
    archetype: "caregiver",
    ageContext: "35-55",
    workContext: "Parent, caregiver, or both",
    incomeContext: "Middle to low",
    locationContext: "Urban or suburban",
    painPoints: [
      "Balancing work, family, and personal time",
      "Lack of access to affordable childcare or eldercare",
      "Feeling disconnected from the community",
      "Difficulty managing household finances",
    ],
    goals: [
      "Streamline daily tasks",
      "Find a supportive network or community",
      "Improve personal well-being and mental health",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "struggling-student",
    name: "The Struggling Student",
    archetype: "student",
    ageContext: "16-25",
    workContext: "High school or college student",
    incomeContext: "Limited, often reliant on family or part-time work",
    locationContext: "Urban, suburban, or rural",
    painPoints: [
      "Difficulty managing time and deadlines",
      "Stress from financial constraints such as tuition and living costs",
      "Lack of clarity about career or life direction",
      "Struggling to access mental health support",
    ],
    goals: [
      "Improve study habits and productivity",
      "Explore career opportunities",
      "Build a support network of peers",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "isolated-elder",
    name: "The Isolated Elder",
    archetype: "elder",
    ageContext: "65+",
    workContext: "Retired",
    incomeContext: "Fixed income, often from social security or pensions",
    locationContext: "Suburban or rural",
    painPoints: [
      "Loneliness and isolation",
      "Physical mobility or health issues",
      "Difficulty navigating technology",
      "Limited access to transportation",
    ],
    goals: [
      "Stay connected with family and friends",
      "Maintain independence at home",
      "Engage in meaningful activities",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [
      "Physical mobility or health issues",
      "Difficulty navigating technology",
    ],
  },
  {
    id: "remote-customer-service-team-lead",
    name: "The Remote Customer Service Team Lead",
    archetype: "team-lead",
    ageContext: null,
    workContext: "Remote customer service team lead with 5+ years experience",
    incomeContext: null,
    locationContext: null,
    painPoints: [
      "Difficulty tracking team productivity and performance",
      "Inefficient tools for managing team tasks and workload",
      "Lack of visibility into individual team members' progress",
    ],
    goals: [
      "Ensure team efficiency and high performance",
      "Monitor team performance and identify areas for improvement",
      "Develop and train team members",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "remote-service-client",
    name: "The Client Hiring Remote Customer Service Teams",
    archetype: "business-owner-client",
    ageContext: null,
    workContext: "Business owner",
    incomeContext: null,
    locationContext: null,
    painPoints: [
      "Difficulty finding and managing a qualified remote customer service team",
      "Lack of visibility into team performance and customer interactions",
      "Challenges in communicating and coordinating with the remote team",
    ],
    goals: [
      "Outsource customer support to a reliable and efficient team",
      "Ensure high customer satisfaction and positive brand reputation",
      "Monitor team performance and address issues",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "aspiring-entrepreneur",
    name: "The Aspiring Entrepreneur",
    archetype: "entrepreneur",
    ageContext: "25-45",
    workContext: "Freelance, small business owner, or startup founder",
    incomeContext: "Variable or limited",
    locationContext: "Urban or global digital nomad",
    painPoints: [
      "Managing inconsistent income",
      "Lack of affordable resources or mentorship",
      "Difficulty balancing work and personal life",
      "Limited marketing or technical skills",
    ],
    goals: [
      "Scale their business or side hustle",
      "Build meaningful connections in their field",
      "Gain financial stability",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "stressed-worker",
    name: "The Stressed Worker",
    archetype: "worker",
    ageContext: "25-55",
    workContext: "Corporate or service industry worker",
    incomeContext: "Middle income",
    locationContext: "Urban or suburban",
    painPoints: [
      "Experiencing burnout or work-life imbalance",
      "Feeling undervalued or stuck in their job",
      "Limited career growth opportunities",
      "Difficulty managing stress and health",
    ],
    goals: [
      "Find career advancement or alternative income sources",
      "Improve work-life balance",
      "Achieve better mental and physical health",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "underserved-global-citizen",
    name: "The Underserved Global Citizen",
    archetype: "underserved-global-citizen",
    ageContext: "18-65",
    workContext: "Laborer, farmer, or local artisan",
    incomeContext: "Low or subsistence",
    locationContext: "Developing regions",
    painPoints: [
      "Limited access to education or training",
      "Unstable or insufficient income sources",
      "Lack of infrastructure for basic needs such as healthcare and clean water",
      "Vulnerability to natural disasters or economic shifts",
    ],
    goals: [
      "Gain access to education and skill-building tools",
      "Improve community infrastructure",
      "Build a sustainable future",
    ],
    vulnerabilities: [
      "Vulnerability to natural disasters or economic shifts",
    ],
    accessibilityConsiderations: [],
  },
  {
    id: "young-dreamer",
    name: "The Young Dreamer",
    archetype: "young-person",
    ageContext: "10-18",
    workContext: "Student",
    incomeContext: "None or minimal allowance",
    locationContext: "Urban, suburban, or rural",
    painPoints: [
      "Struggles with self-identity and peer pressure",
      "Limited access to extracurricular resources",
      "Anxiety about climate change and the future",
      "Difficulty communicating feelings to adults",
    ],
    goals: [
      "Express creativity and individuality",
      "Find role models or mentorship",
      "Learn life skills for independence",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "remote-worker",
    name: "The Remote Worker",
    archetype: "remote-worker",
    ageContext: "25-55",
    workContext: "Remote or hybrid professional",
    incomeContext: "Middle income",
    locationContext: "Urban, suburban, or rural",
    painPoints: [
      "Isolation and lack of face-to-face interaction",
      "Difficulty managing productivity and home distractions",
      "Lack of ergonomic workspaces or equipment",
      "Blurred boundaries between work and personal life",
    ],
    goals: [
      "Enhance productivity and maintain mental health",
      "Stay connected with colleagues",
      "Balance work with family or personal interests",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "refugee-or-displaced-individual",
    name: "The Refugee or Displaced Individual",
    archetype: "displaced-person",
    ageContext: "18-50",
    workContext: "Variable or unemployed",
    incomeContext: "None or minimal",
    locationContext: "Refugee camps or temporary shelters",
    painPoints: [
      "Lack of access to basic necessities such as food, water, and shelter",
      "Uncertainty about legal status or future opportunities",
      "Separation from family and support systems",
      "Limited educational or job opportunities",
    ],
    goals: [
      "Rebuild a stable and secure life",
      "Access resources to gain skills and employment",
      "Reconnect with lost family members",
    ],
    vulnerabilities: [
      "Uncertainty about legal status or future opportunities",
      "Separation from family and support systems",
    ],
    accessibilityConsiderations: [],
  },
  {
    id: "underemployed-worker",
    name: "The Underemployed Worker",
    archetype: "underemployed-worker",
    ageContext: "20-60",
    workContext: "Part-time or temporary jobs",
    incomeContext: "Low",
    locationContext: "Urban or suburban",
    painPoints: [
      "Struggling to make ends meet with insufficient hours or wages",
      "Anxiety about losing work or job instability",
      "Limited time or resources for skill-building",
      "Lack of affordable childcare or healthcare",
    ],
    goals: [
      "Find stable, full-time employment",
      "Learn new skills to improve employability",
      "Achieve financial independence",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "tech-savvy-innovator",
    name: "The Tech-Savvy Innovator",
    archetype: "technical-innovator",
    ageContext: "20-40",
    workContext: "Developer, designer, or creative professional",
    incomeContext: "Variable",
    locationContext: "Urban or digital nomad",
    painPoints: [
      "High competition in creative or tech industries",
      "Difficulty standing out or gaining recognition",
      "Mental health challenges due to stress and overwork",
      "Finding meaningful projects that align with values",
    ],
    goals: [
      "Build a successful portfolio or personal brand",
      "Collaborate with like-minded individuals",
      "Work on projects with a positive global impact",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "small-town-resident",
    name: "The Small Town Resident",
    archetype: "rural-community-member",
    ageContext: "30-70",
    workContext: "Small business owner, farmer, or community worker",
    incomeContext: "Low to middle",
    locationContext: "Rural or small town",
    painPoints: [
      "Limited access to technology and infrastructure",
      "Economic struggles in shrinking communities",
      "Difficulty accessing specialized healthcare or education",
      "Disconnection from broader cultural opportunities",
    ],
    goals: [
      "Strengthen local economy and preserve community identity",
      "Improve access to resources and services",
      "Create opportunities for the next generation",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "urban-commuter",
    name: "The Urban Commuter",
    archetype: "urban-worker",
    ageContext: "20-60",
    workContext: "Office worker, service industry, or skilled labor",
    incomeContext: "Middle",
    locationContext: "Major city",
    painPoints: [
      "Long and stressful commutes",
      "High cost of living",
      "Limited time for personal or family activities",
      "Exposure to urban pollution or safety concerns",
    ],
    goals: [
      "Save time and money on daily travel",
      "Improve work-life balance",
      "Contribute to sustainable city living",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "aspiring-artist-or-creator",
    name: "The Aspiring Artist or Creator",
    archetype: "creator",
    ageContext: "18-40",
    workContext: "Freelancer or hobbyist",
    incomeContext: "Variable or low",
    locationContext: "Urban or suburban",
    painPoints: [
      "Struggling to monetize creative skills",
      "Difficulty finding an audience or platform",
      "Creative blocks or burnout",
      "Lack of affordable tools or resources",
    ],
    goals: [
      "Share their art with a wider audience",
      "Gain financial stability through creativity",
      "Connect with a supportive artistic community",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
  {
    id: "environmental-advocate",
    name: "The Environmental Advocate",
    archetype: "environmental-advocate",
    ageContext: "20-50",
    workContext: "Activist, educator, or sustainability professional",
    incomeContext: "Variable",
    locationContext: "Urban or rural",
    painPoints: [
      "Frustration with lack of global action on climate change",
      "Limited reach or impact of individual efforts",
      "Difficulty engaging the public in sustainable practices",
      "Burnout from activism work",
    ],
    goals: [
      "Promote systemic change for a sustainable future",
      "Empower communities to adopt greener habits",
      "Collaborate with others to scale impact",
    ],
    vulnerabilities: [],
    accessibilityConsiderations: [],
  },
] as const;
